package org.src.components.map;

public enum DisplayMode {
	// TODO: DO NOT CHANGE THE ORDER
	// TODO: REMEMBER TO UPDATE THE MODE SELECTION
	TERRAIN,
	POPULATION,
	ELEVATION,
	POLITICAL,
	ETHNICITY,
	DEMOGRAPHIC;
}
